import { getApiBase } from '../../utils/api';

export const API_BASE = getApiBase();

export const BROKERS = [
  {
    id: 'angel_one',
    name: 'Angel One',
    subtitle: 'SmartAPI Connect',
    logo: '🪬',
    color: '#F97316',
    supported: true,
    fields: [
      { key: 'api_key',     label: 'API Key',      placeholder: 'e.g. UgegfQMq',          type: 'password', help: 'SmartAPI Key from Angel One developer portal' },
      { key: 'client_id',   label: 'Client ID',    placeholder: 'e.g. M62446252',        type: 'text',     help: 'Your Angel One login client code' },
      { key: 'password',    label: 'PIN / Password', placeholder: '4-digit MPIN or Login Password', type: 'password', help: 'Your Angel One login MPIN or trading password' },
      { key: 'totp_secret', label: 'TOTP Secret (Base32)', placeholder: 'e.g. RP2CFZHVER26CNJLUMTOFFBZZE', type: 'password', help: 'Base32 TOTP QR secret key from 2FA setup' },
    ],
  },
  {
    id: 'zerodha',
    name: 'Zerodha',
    subtitle: 'Kite Connect API',
    logo: '🪁',
    color: '#387ED1',
    supported: true,
    fields: [
      { key: 'api_key',      label: 'API Key',       placeholder: 'e.g. abcd1234efgh5678', type: 'password', help: 'Kite Connect API Key from developer portal' },
      { key: 'api_secret',   label: 'API Secret',    placeholder: 'e.g. 32-character secret', type: 'password', help: 'Kite Connect API Secret' },
      { key: 'access_token', label: 'Access Token / Enctoken', placeholder: 'Daily Access Token or Enctoken', type: 'password', help: 'Session access token generated upon daily login' },
    ],
  },
  {
    id: 'upstox',
    name: 'Upstox',
    subtitle: 'Upstox Pro v2',
    logo: '⚡',
    color: '#7C3AED',
    supported: true,
    fields: [
      { key: 'api_key',      label: 'API Key (Client ID)', placeholder: 'Upstox App Client ID', type: 'password', help: 'Client ID from Upstox Developer Portal' },
      { key: 'api_secret',   label: 'API Secret',    placeholder: 'Upstox App Secret Key', type: 'password', help: 'Secret Key from Upstox Developer Portal' },
      { key: 'redirect_uri', label: 'Redirect URI',  placeholder: 'https://127.0.0.1:8000/api/broker/callback', type: 'text', help: 'OAuth Redirect URI' },
      { key: 'access_token', label: 'Access Token',  placeholder: 'Daily OAuth Access Token', type: 'password', help: 'OAuth2 access token for data and orders' },
    ],
  },
  {
    id: 'fyers',
    name: 'Fyers',
    subtitle: 'Fyers API v3',
    logo: '🔥',
    color: '#EAB308',
    supported: true,
    fields: [
      { key: 'app_id',       label: 'App ID',        placeholder: 'e.g. XXXXXX-100', type: 'text', help: 'Fyers App ID from API Dashboard' },
      { key: 'secret_key',   label: 'Secret Key',    placeholder: 'Fyers App Secret Key', type: 'password', help: 'Secret Key from Fyers API dashboard' },
      { key: 'access_token', label: 'Access Token',  placeholder: 'Daily 2FA Auth Token', type: 'password', help: 'Access token generated after daily login' },
    ],
  },
];

export const AI_PROVIDERS_META = [
  {
    id: 'gemini',
    name: 'Google Gemini',
    logo: '✨',
    color: '#818CF8',
    regex: /^AIza[A-Za-z0-9_-]{35}$/,
    defaultModel: 'gemini-3.6-flash',
    speed: '85ms (Ultra Fast)',
    quality: 'State-of-the-Art',
    cost: 'Free Tier Available',
    freeLimit: '15 RPM / 1M TPM Free',
    models: [
      { id: 'gemini-3.6-flash', name: 'Gemini 3.6 Flash', recommended: true, free: true },
      { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', recommended: false, free: true },
      { id: 'gemini-2.5-pro',   name: 'Gemini 2.5 Pro',   recommended: false, free: false },
      { id: 'gemini-pro',       name: 'Gemini 1.0 Pro',   recommended: false, free: true },
    ],
    signupUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    logo: '🧠',
    color: '#10B981',
    regex: /^sk-[A-Za-z0-9_-]{20,}$/,
    defaultModel: 'gpt-4o-mini',
    speed: '160ms (Fast)',
    quality: 'Exceptional',
    cost: '$0.15 / 1M Tokens',
    freeLimit: 'Pay-as-you-go',
    models: [
      { id: 'gpt-4o-mini',         name: 'GPT-4o Mini',              recommended: true, free: false },
      { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B (Open-MoE)',  recommended: false, free: true },
      { id: 'gpt-4o',              name: 'GPT-4o Flagship',          recommended: false, free: false },
      { id: 'o3-mini',             name: 'o3 Mini (Reasoning)',      recommended: false, free: false },
      { id: 'gpt-3.5-turbo',       name: 'GPT-3.5 Turbo',            recommended: false, free: false },
    ],
    signupUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    logo: '🪐',
    color: '#F97316',
    regex: /^sk-ant-[A-Za-z0-9_-]{20,}$/,
    defaultModel: 'claude-3-5-sonnet-20241022',
    speed: '240ms (Medium)',
    quality: 'State-of-the-Art',
    cost: '$3.00 / 1M Tokens',
    freeLimit: 'Pay-as-you-go',
    models: [
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet', recommended: true, free: false },
      { id: 'claude-3-haiku-20240307',    name: 'Claude 3 Haiku',    recommended: false, free: false },
      { id: 'claude-3-opus-20240229',     name: 'Claude 3 Opus',     recommended: false, free: false },
    ],
    signupUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    logo: '🌪️',
    color: '#F59E0B',
    regex: /^mist-[A-Za-z0-9_-]{20,}$/,
    defaultModel: 'mistral-small-latest',
    speed: '140ms (Fast)',
    quality: 'Very High',
    cost: 'Free Tier Available',
    freeLimit: '1 RPS Free Tier',
    models: [
      { id: 'mistral-small-latest',  name: 'Mistral Small',  recommended: true, free: true },
      { id: 'mistral-medium-latest', name: 'Mistral Medium', recommended: false, free: false },
      { id: 'mistral-large-latest',  name: 'Mistral Large',  recommended: false, free: false },
      { id: 'open-mistral-7b',       name: 'Mistral 7B',     recommended: false, free: true },
    ],
    signupUrl: 'https://console.mistral.ai/api-keys',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    logo: '🌊',
    color: '#06B6D4',
    regex: /^CO[A-Za-z0-9_-]{24,}$/,
    defaultModel: 'command-r-plus',
    speed: '190ms (Fast)',
    quality: 'High (RAG-Tuned)',
    cost: 'Trial Keys Free',
    freeLimit: '1,000 requests/mo',
    models: [
      { id: 'command-r-plus', name: 'Command R+',  recommended: true, free: true },
      { id: 'command-r',      name: 'Command R',   recommended: false, free: true },
      { id: 'command-light',  name: 'Command Light', recommended: false, free: true },
    ],
    signupUrl: 'https://dashboard.cohere.com/api-keys',
  },
  {
    id: 'groq',
    name: 'Groq LPU',
    logo: '⚡',
    color: '#EC4899',
    regex: /^gsk_[A-Za-z0-9_-]{30,}$/,
    defaultModel: 'llama-3.3-70b-versatile',
    speed: '25ms (Lightning Fast)',
    quality: 'Very High',
    cost: 'Free Beta Tier',
    freeLimit: '30 RPM Free',
    models: [
      { id: 'llama-3.3-70b-versatile',       name: 'Llama 3.3 70B Versatile',     recommended: true, free: true },
      { id: 'openai/gpt-oss-120b',           name: 'OpenAI GPT-OSS 120B (LPU)',   recommended: false, free: true },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill 70B',     recommended: false, free: true },
      { id: 'llama-3.1-8b-instant',          name: 'Llama 3.1 8B Instant',        recommended: false, free: true },
      { id: 'llama-3.1-70b-versatile',       name: 'Llama 3.1 70B Versatile',     recommended: false, free: true },
      { id: 'mixtral-8x7b-32768',            name: 'Mixtral 8x7B (32k Context)',  recommended: false, free: true },
      { id: 'gemma2-9b-it',                  name: 'Gemma 2 9B IT',               recommended: false, free: true },
      { id: 'llama3-70b-8192',               name: 'Llama 3 70B (Legacy 8k)',     recommended: false, free: true },
      { id: 'llama3-8b-8192',                name: 'Llama 3 8B (Legacy 8k)',      recommended: false, free: true },
    ],
    signupUrl: 'https://console.groq.com/keys',
  },
];
